### ISSUE TITLE
Unable to deploy due to error estimating gas. Where should I edit? Thank you

### ISSUE THREAD

**Issue by Stcetjo** [vfat-tools/adventure-party#2]
Unable to deploy due to error estimating gas. Where should I edit? Thank you this is awesome!
Here's the return: 

Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="estimateGas", transaction={"from":"0xBf42034D91a1Cb630f4F332a7A14039eda0747D6",

**Comment by vfat0** [comment]
did the test deploy script work? (without `--network fantom`)

**Comment by Stcetjo** [comment]
No it didn't. Did I miss something? Here's the log: 

Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Error: Transaction reverted without a reason string
    at <UnrecognizedContract>.<unknown> (0xce761d788df608bd21bdd59d6f4b54b2e27f25bb)
    at AdventureParty.constructor (contracts/AdventureParty.sol:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EthModule._estimateGasAction (/home/stjopey/adventureparty/adventure-party/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
    at HardhatNetworkProvider.request (/home/stjopey/adventureparty/adventure-party/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:108:18)
    at EthersProviderWrapper.send (/home/stjopey/adventureparty/adventure-party/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

**Comment by vfat0** [comment]
are you using the latest version? (`git pull`) it doesn't mint in the constructor any more

**Comment by Stcetjo** [comment]
many thanks can't wait to try it out!
